version: "3.9"
services:
  
  dilithium-pqcrypto:
    image: dilithium-pqcrypto
    build:
      context: ./suites/go/dilithium-pqcrypto
      dockerfile: Dockerfile
    volumes:
      - ./data:/data

  
  